//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_language")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub script_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_background_languages::Entity")]
    CharacterBackgroundLanguages,
    #[sea_orm(
        belongs_to = "super::character_script::Entity",
        from = "Column::ScriptId",
        to = "super::character_script::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CharacterScript,
    #[sea_orm(has_many = "super::race_race_languages::Entity")]
    RaceRaceLanguages,
}

impl Related<super::character_background_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterBackgroundLanguages.def()
    }
}

impl Related<super::character_script::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterScript.def()
    }
}

impl Related<super::race_race_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceLanguages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
