//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_proficiency")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub proficiency_type: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_attack::Entity")]
    CharacterAttack,
    #[sea_orm(has_many = "super::character_character_proficiencies::Entity")]
    CharacterCharacterProficiencies,
    #[sea_orm(has_many = "super::character_characterclass_proficiencies::Entity")]
    CharacterCharacterclassProficiencies,
    #[sea_orm(has_many = "super::character_npc_proficiencies::Entity")]
    CharacterNpcProficiencies,
}

impl Related<super::character_attack::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterAttack.def()
    }
}

impl Related<super::character_character_proficiencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterCharacterProficiencies.def()
    }
}

impl Related<super::character_characterclass_proficiencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterCharacterclassProficiencies.def()
    }
}

impl Related<super::character_npc_proficiencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpcProficiencies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
