//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_background_features")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub background_id: i64,
    pub feature_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::character_background::Entity",
        from = "Column::BackgroundId",
        to = "super::character_background::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CharacterBackground,
    #[sea_orm(
        belongs_to = "super::character_feature::Entity",
        from = "Column::FeatureId",
        to = "super::character_feature::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CharacterFeature,
}

impl Related<super::character_background::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterBackground.def()
    }
}

impl Related<super::character_feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterFeature.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
