//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_inventorytool")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub inventoryitem_ptr_id: i64,
    pub gear_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::character_inventoryitem::Entity",
        from = "Column::InventoryitemPtrId",
        to = "super::character_inventoryitem::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CharacterInventoryitem,
    #[sea_orm(
        belongs_to = "super::character_tool::Entity",
        from = "Column::GearId",
        to = "super::character_tool::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CharacterTool,
}

impl Related<super::character_inventoryitem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterInventoryitem.def()
    }
}

impl Related<super::character_tool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterTool.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
