//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_characterclass")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub hit_die: Option<String>,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub skill_number: i32,
    pub multiclass_skill_number: i32,
    #[sea_orm(column_type = "Text")]
    pub equipment_choices: String,
    pub major_saving_throw: String,
    pub minor_saving_throw: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_characterclass_proficiencies::Entity")]
    CharacterCharacterclassProficiencies,
    #[sea_orm(has_many = "super::character_classandlevel::Entity")]
    CharacterClassandlevel,
}

impl Related<super::character_characterclass_proficiencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterCharacterclassProficiencies.def()
    }
}

impl Related<super::character_classandlevel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterClassandlevel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
