//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character_npc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub slug: String,
    pub thumbnail_id: Option<String>,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub size: Option<String>,
    pub race_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub markdown_notes: Option<String>,
    pub lock_time: Option<DateTimeWithTimeZone>,
    pub lock_user_id: Option<i64>,
    pub image_ids: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_npc_associations::Entity")]
    CharacterNpcAssociations,
    #[sea_orm(has_many = "super::character_npc_features_and_traits::Entity")]
    CharacterNpcFeaturesAndTraits,
    #[sea_orm(has_many = "super::character_npc_logs::Entity")]
    CharacterNpcLogs,
    #[sea_orm(has_many = "super::character_npc_proficiencies::Entity")]
    CharacterNpcProficiencies,
    #[sea_orm(
        belongs_to = "super::nucleus_user::Entity",
        from = "Column::LockUserId",
        to = "super::nucleus_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NucleusUser,
    #[sea_orm(
        belongs_to = "super::race_race::Entity",
        from = "Column::RaceId",
        to = "super::race_race::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RaceRace,
}

impl Related<super::character_npc_associations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpcAssociations.def()
    }
}

impl Related<super::character_npc_features_and_traits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpcFeaturesAndTraits.def()
    }
}

impl Related<super::character_npc_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpcLogs.def()
    }
}

impl Related<super::character_npc_proficiencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpcProficiencies.def()
    }
}

impl Related<super::nucleus_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NucleusUser.def()
    }
}

impl Related<super::race_race::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
