//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "django_admin_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub action_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub object_id: Option<String>,
    pub object_repr: String,
    pub action_flag: i16,
    #[sea_orm(column_type = "Text")]
    pub change_message: String,
    pub content_type_id: Option<i32>,
    pub user_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::django_content_type::Entity",
        from = "Column::ContentTypeId",
        to = "super::django_content_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DjangoContentType,
    #[sea_orm(
        belongs_to = "super::nucleus_user::Entity",
        from = "Column::UserId",
        to = "super::nucleus_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NucleusUser,
}

impl Related<super::django_content_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DjangoContentType.def()
    }
}

impl Related<super::nucleus_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NucleusUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
