//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item_item_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub item_id: i64,
    pub gamelog_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_item::Entity",
        from = "Column::ItemId",
        to = "super::item_item::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemItem,
    #[sea_orm(
        belongs_to = "super::nucleus_gamelog::Entity",
        from = "Column::GamelogId",
        to = "super::nucleus_gamelog::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NucleusGamelog,
}

impl Related<super::item_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemItem.def()
    }
}

impl Related<super::nucleus_gamelog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NucleusGamelog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
