//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "place_placerace")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub percent: f64,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    pub place_id: i64,
    pub race_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::place_place::Entity",
        from = "Column::PlaceId",
        to = "super::place_place::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlacePlace,
    #[sea_orm(
        belongs_to = "super::race_race::Entity",
        from = "Column::RaceId",
        to = "super::race_race::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RaceRace,
}

impl Related<super::place_place::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlacePlace.def()
    }
}

impl Related<super::race_race::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
