//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "race_abilityscoreincrease")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ability_score: String,
    pub increase: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::race_race_ability_score_increases::Entity")]
    RaceRaceAbilityScoreIncreases,
}

impl Related<super::race_race_ability_score_increases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceAbilityScoreIncreases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
