//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "race_trait")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::race_race_traits::Entity")]
    RaceRaceTraits,
}

impl Related<super::race_race_traits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceTraits.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
