//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "race_race")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created: DateTimeWithTimeZone,
    pub updated: DateTimeWithTimeZone,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub slug: String,
    pub thumbnail_id: Option<String>,
    pub age_of_adulthood: Option<i32>,
    pub life_expectancy: Option<i32>,
    pub alignment: Option<String>,
    pub size: Option<String>,
    pub speed: Option<i32>,
    pub base_race_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub markdown_notes: Option<String>,
    pub lock_time: Option<DateTimeWithTimeZone>,
    pub lock_user_id: Option<i64>,
    pub image_ids: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_character::Entity")]
    CharacterCharacter,
    #[sea_orm(has_many = "super::character_npc::Entity")]
    CharacterNpc,
    #[sea_orm(
        belongs_to = "super::nucleus_user::Entity",
        from = "Column::LockUserId",
        to = "super::nucleus_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NucleusUser,
    #[sea_orm(has_many = "super::place_placerace::Entity")]
    PlacePlacerace,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::BaseRaceId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::race_race_ability_score_increases::Entity")]
    RaceRaceAbilityScoreIncreases,
    #[sea_orm(has_many = "super::race_race_languages::Entity")]
    RaceRaceLanguages,
    #[sea_orm(has_many = "super::race_race_logs::Entity")]
    RaceRaceLogs,
    #[sea_orm(has_many = "super::race_race_traits::Entity")]
    RaceRaceTraits,
}

impl Related<super::character_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterCharacter.def()
    }
}

impl Related<super::character_npc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterNpc.def()
    }
}

impl Related<super::nucleus_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NucleusUser.def()
    }
}

impl Related<super::place_placerace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlacePlacerace.def()
    }
}

impl Related<super::race_race_ability_score_increases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceAbilityScoreIncreases.def()
    }
}

impl Related<super::race_race_languages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceLanguages.def()
    }
}

impl Related<super::race_race_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceLogs.def()
    }
}

impl Related<super::race_race_traits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaceRaceTraits.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
